CREATE DATABASE JavaApp
GO

USE JavaApp
GO

CREATE TABLE tb_ROLE
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	RoleName NVARCHAR(128) NOT NULL,
	STT BIT
)
GO

CREATE TABLE tb_FUNCTION
(
	ID VARCHAR(128) PRIMARY KEY,
	FunctionName NVARCHAR(128) NOT NULL,
	STT BIT
)
GO

CREATE TABLE tb_ROLEFUNCTION
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	IDRole BIGINT,
	IDFunction VARCHAR(128),
	STT BIT

	FOREIGN KEY (IDRole) REFERENCES tb_ROLE(ID),
	FOREIGN KEY (IDFunction) REFERENCES tb_FUNCTION(ID)
)
GO

CREATE TABLE tb_USER
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	UserName VARCHAR(128),
	Password VARCHAR(128),
	Name NVARCHAR(128) NOT NULL,
	Phone VARCHAR(20),
	Address NVARCHAR(MAX),
	Email VARCHAR(128),
	RoleID BIGINT NOT NULL,
	STT BIT NOT NULL,

	FOREIGN KEY (RoleID) REFERENCES dbo.tb_ROLE(ID)
)
GO

CREATE TABLE tb_SUPLIER
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	SuplierName NVARCHAR(MAX),
	Address NVARCHAR(MAX),
	Phone VARCHAR(20),
	Email VARCHAR(128),
	STT BIT NOT NULL
)
GO

CREATE TABLE tb_PRODUCT
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	ProductName NVARCHAR(MAX),
	Price DECIMAL(19,4),
	SL INT NOT NULL DEFAULT(0),
	Suplier BIGINT NOT NULL,
	STT BIT NOT NULL,

	FOREIGN KEY (Suplier) REFERENCES dbo.tb_SUPLIER(ID)
)
GO

CREATE TABLE tb_BILL
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	UserCreate BIGINT NOT NULL,
	DateCreate VARCHAR(50),

	FOREIGN KEY (UserCreate) REFERENCES dbo.tb_USER(ID)
)
GO

CREATE TABLE tb_BILLINFO
(
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	BillID BIGINT NOT NULL,
	Product BIGINT NOT NULL,
	Price DECIMAL(19,4),
	SL INT NOT NULL,

	FOREIGN KEY (Product) REFERENCES dbo.tb_PRODUCT(ID),
	FOREIGN KEY (BillID) REFERENCES dbo.tb_BILL(ID)
)
